-- CREATE DATABASE IF NOT EXISTS inditex_locker;

-- USE inditex_locker;

INSERT INTO productos (nombre, stock) VALUES ('Camiseta', 10);
INSERT INTO productos (nombre, stock) VALUES ('Pantalon', 18);
INSERT INTO productos (nombre, stock) VALUES ('Clips', 200);
INSERT INTO productos (nombre, stock) VALUES ('Bolso', 3);

INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Johnson', 14, 37);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Rodriguez', 46, 44);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Brown', 31, 23);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Brown', 10, 29);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Martinez', 43, 29);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Casey Smith', 43, 31);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Brown', 42, 41);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jordan Williams', 18, 6);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Garcia', 9, 20);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Avery Davis', 4, 0);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Johnson', 31, 21);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Avery Brown', 25, 37);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Casey Davis', 15, 36);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Jones', 11, 25);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Garcia', 0, 12);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Taylor Williams', 34, 21);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Williams', 2, 9);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Sam Williams', 38, 25);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Taylor Martinez', 48, 48);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Avery Rodriguez', 40, 32);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Martinez', 41, 27);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Davis', 45, 14);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Avery Williams', 6, 49);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Smith', 46, 21);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Jones', 24, 12);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Miller', 20, 37);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Johnson', 4, 6);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Casey Garcia', 29, 20);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Johnson', 34, 30);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Rodriguez', 25, 26);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Taylor Jones', 1, 26);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jordan Brown', 6, 23);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Garcia', 36, 38);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Williams', 23, 40);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Williams', 18, 8);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Rodriguez', 40, 42);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Williams', 18, 36);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Alex Miller', 43, 28);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Morgan Rodriguez', 17, 34);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Taylor Williams', 4, 12);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Sam Smith', 38, 8);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Avery Smith', 33, 35);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jordan Williams', 34, 27);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Johnson', 30, 15);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Miller', 15, 23);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Miller', 17, 39);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Riley Smith', 38, 6);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Reese Garcia', 11, 17);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jamie Brown', 46, 24);
INSERT INTO clientes(nombre, direccionx, direcciony) VALUES ('Jordan Williams', 26, 3);

INSERT INTO lockers(direccionx, direcciony) VALUES (4, 44);
INSERT INTO lockers(direccionx, direcciony) VALUES (18, 46);
INSERT INTO lockers(direccionx, direcciony) VALUES (24, 6);
INSERT INTO lockers(direccionx, direcciony) VALUES (13, 26);
INSERT INTO lockers(direccionx, direcciony) VALUES (25, 7);
INSERT INTO lockers(direccionx, direcciony) VALUES (23, 23);
INSERT INTO lockers(direccionx, direcciony) VALUES (2, 17);
INSERT INTO lockers(direccionx, direcciony) VALUES (46, 43);
INSERT INTO lockers(direccionx, direcciony) VALUES (14, 30);
INSERT INTO lockers(direccionx, direcciony) VALUES (33, 32);
INSERT INTO lockers(direccionx, direcciony) VALUES (15, 33);
INSERT INTO lockers(direccionx, direcciony) VALUES (29, 34);
INSERT INTO lockers(direccionx, direcciony) VALUES (13, 16);
INSERT INTO lockers(direccionx, direcciony) VALUES (15, 13);
INSERT INTO lockers(direccionx, direcciony) VALUES (23, 22);
INSERT INTO lockers(direccionx, direcciony) VALUES (10, 13);
INSERT INTO lockers(direccionx, direcciony) VALUES (25, 34);
INSERT INTO lockers(direccionx, direcciony) VALUES (33, 45);
INSERT INTO lockers(direccionx, direcciony) VALUES (10, 12);
INSERT INTO lockers(direccionx, direcciony) VALUES (17, 11);
INSERT INTO lockers(direccionx, direcciony) VALUES (20, 25);
INSERT INTO lockers(direccionx, direcciony) VALUES (16, 1);
INSERT INTO lockers(direccionx, direcciony) VALUES (6, 35);
INSERT INTO lockers(direccionx, direcciony) VALUES (14, 40);
INSERT INTO lockers(direccionx, direcciony) VALUES (12, 36);
INSERT INTO lockers(direccionx, direcciony) VALUES (14, 42);
INSERT INTO lockers(direccionx, direcciony) VALUES (27, 9);
INSERT INTO lockers(direccionx, direcciony) VALUES (30, 45);
INSERT INTO lockers(direccionx, direcciony) VALUES (30, 19);
INSERT INTO lockers(direccionx, direcciony) VALUES (26, 48);

INSERT INTO obstaculos(direccionx, direcciony) VALUES (21, 36);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (26, 17);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (35, 46);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (6, 50);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (17, 31);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (17, 4);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (33, 34);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (37, 29);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (38, 2);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (45, 41);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (15, 41);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (18, 5);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (12, 18);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (29, 13);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (40, 7);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (31, 7);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (31, 6);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (3, 38);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (8, 31);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (8, 20);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (32, 23);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (1, 34);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (25, 15);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (35, 49);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (28, 38);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (35, 45);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (28, 25);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (32, 25);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (35, 6);
INSERT INTO obstaculos(direccionx, direcciony) VALUES (12, 28);
